from _typeshed import Incomplete

http: Incomplete

class CardanoPoolChecker:
    def __init__(self, updates: Incomplete | None = ..., register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    @property
    def pools(self): ...
    @property
    def updates(self): ...
    @property
    def register(self): ...
    @property
    def translations(self): ...
    @property
    def last_block_time(self): ...
    @property
    def registered_currently_sharing_relay_hostname(self): ...
    @property
    def registered_currently_sharing_relay_ipv4(self): ...
    @property
    def registered_currently_sharing_relay_ipv6(self): ...
    @property
    def registered_currently_sharing_meta_json_homepage(self): ...
    @property
    def registered_currently_sharing_meta_url(self): ...
    @property
    def registered_currently_sharing_owners(self): ...
    @property
    def registered_currently_sharing_reward_addr(self): ...
    @property
    def registered_sharing_relay_hostname(self): ...
    @property
    def registered_sharing_relay_ipv4(self): ...
    @property
    def registered_sharing_relay_ipv6(self): ...
    @property
    def registered_sharing_meta_json_homepage(self): ...
    @property
    def registered_sharing_meta_url(self): ...
    @property
    def registered_sharing_owners(self): ...
    @property
    def registered_sharing_reward_addr(self): ...
    def info(self) -> None: ...
    def update(self) -> None: ...
    @classmethod
    def build_pools(cls): ...
    def set_pools(self) -> None: ...
    @classmethod
    def build_updates(cls, since: int = ...): ...
    def set_updates(self, since: Incomplete | None = ...) -> None: ...
    @staticmethod
    def build_register(updates=..., register=...): ...
    def set_register(self, updates: Incomplete | None = ...) -> None: ...
    @classmethod
    def build_translations(cls, register=..., translations=...): ...
    def set_translations(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    def set_all_sharing(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    def set_registered_currently_sharing(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    def set_registered_sharing(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_currently_sharing_relay_hostname(register=...): ...
    def set_registered_currently_sharing_relay_hostname(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_currently_sharing_relay_ipv4(register=..., translations=...): ...
    def set_registered_currently_sharing_relay_ipv4(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    @classmethod
    def find_registered_currently_sharing_relay_ipv6(cls, register=..., translations=...): ...
    def set_registered_currently_sharing_relay_ipv6(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    @classmethod
    def find_registered_currently_sharing_meta_json_homepage(cls, register=...): ...
    def set_registered_currently_sharing_meta_json_homepage(self, register: Incomplete | None = ...) -> None: ...
    @classmethod
    def find_registered_currently_sharing_meta_url(cls, register=...): ...
    def set_registered_currently_sharing_meta_url(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_currently_sharing_owners(register=...): ...
    def set_registered_currently_sharing_owners(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_currently_sharing_reward_addr(register=...): ...
    def set_registered_currently_sharing_reward_addr(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_sharing_relay_hostname(register=...): ...
    def set_registered_sharing_relay_hostname(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_sharing_relay_ipv4(register=..., translations=...): ...
    def set_registered_sharing_relay_ipv4(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    @classmethod
    def find_registered_sharing_relay_ipv6(cls, register=..., translations=...): ...
    def set_registered_sharing_relay_ipv6(self, register: Incomplete | None = ..., translations: Incomplete | None = ...) -> None: ...
    @classmethod
    def find_registered_sharing_meta_json_homepage(cls, register=...): ...
    def set_registered_sharing_meta_json_homepage(self, register: Incomplete | None = ...) -> None: ...
    @classmethod
    def find_registered_sharing_meta_url(cls, register=...): ...
    def set_registered_sharing_meta_url(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_sharing_owners(register=...): ...
    def set_registered_sharing_owners(self, register: Incomplete | None = ...) -> None: ...
    @staticmethod
    def find_registered_sharing_reward_addr(register=...): ...
    def set_registered_sharing_reward_addr(self, register: Incomplete | None = ...) -> None: ...

def main() -> None: ...
