name: Update Pool Definitions

on:
  schedule:
    - cron: '00 0 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Trigger workflow manually' 

jobs:
  update_pools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token:  ${{ secrets.BOT_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        cache: 'poetry'
    - name: Update JSON files
      run: |
        python cardano_pool_checker/__main__.py
    - name: Commit to repo
      run: |
        git config --global user.email '${{ secrets.BOT_EMAIL }}'
        git config --global user.name 'blockopszone-bot'
        git add .
        git commit -m "Scheduled update on $(date +'%d/%m/%Y %H:%M:%S')"
        git push